export const environment = {
    production: false,
    drawingGrid: {
        gapX: 150,
        gapY: 150,
    },
    drawingElements: {
        activities: {
            radius: 7,
            width: 30,
            height: 30,
            bgColor: 'white',
            bgOpacity: '1',
            strokeColor: 'black',
            strokeOpacity: '1',
            strokeWidth: 2,
        },
        boxes: {
            bgColor: '#fdf5e6',
            // bgColor: '#eeeeee',
            bgOpacity: '1',
            strokeColor: 'black',
            strokeOpacity: '1',
            strokeWidth: 4,
        },
        transitions: {
            width: 30,
            height: 30,
            bgColor: 'white',
            bgOpacity: '1',
            strokeColor: 'black',
            strokeOpacity: '1',
            strokeWidth: 2,
        },
        invisibleTransitions: {
            width: 15,
            height: 30,
            bgColor: 'black',
            bgOpacity: '1',
            strokeColor: 'black',
            strokeOpacity: '1',
            strokeWidth: 2,
        },
        places: {
            radius: 15,
            bgColor: 'white',
            bgOpacity: '1',
            strokeColor: 'black',
            strokeOpacity: '1',
            strokeWidth: 2,
        },
        arcs: {
            color: 'black',
            width: 1,
        },
    },
};
