export const environment = {
    production: false,
    drawingGrid: {
        gapX: 125,
        gapY: 125,
    },
    drawingElements: {
        activities: {
            width: 40,
            height: 40,
            radius: 7,
            bgColor: 'white',
            bgOpacity: '1',
            strokeColor: 'black',
            strokeOpacity: '1',
            strokeWidth: 2,
        },
        boxes: {
            bgColor: 'lightgrey',
            bgOpacity: '1',
            strokeColor: 'black',
            strokeOpacity: '1',
            strokeWidth: 4,
        },
        transitions: {
            width: 40,
            height: 40,
            bgColor: 'white',
            bgOpacity: '1',
            strokeColor: 'black',
            strokeOpacity: '1',
            strokeWidth: 2,
        },
        invisibleTransitions: {
            width: 20,
            height: 40,
            bgColor: 'black',
            bgOpacity: '1',
            strokeColor: 'black',
            strokeOpacity: '1',
            strokeWidth: 2,
        },
        places: {
            radius: 20,
            bgColor: 'white',
            bgOpacity: '1',
            strokeColor: 'black',
            strokeOpacity: '1',
            strokeWidth: 2,
        },
        arcs: {
            color: 'black',
            width: 1,
        },
    },
};
